<a href="https://colab.research.google.com/github/a-forty-two/PWC_22_May_23/blob/main/ML_001.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
# data manipulation-> read, slice/dice, rearrange data!
# return values-> DATAFRAME -> rectangular dataset -> rows and columns-> TABLE

data = pd.read_csv("https://raw.githubusercontent.com/a-forty-two/cylons/master/data.csv")

In [2]:
data.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [4]:
data.head(3)

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.8,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.6,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.9,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.8,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.0,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.5,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN

In [6]:
data.tail(2)

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
567,927241,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.3514,0.152,...,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.265,0.4087,0.12400,NaN
568,92751,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.0000,0.000,...,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.000,0.2871,0.07039,NaN

Column Selection

In [7]:
cols_to_select = ['id', 'diagnosis']
newdata = data [ cols_to_select ]
newdata.head()

         id diagnosis
0    842302         M
1    842517         M
2  84300903         M
3  84348301         M
4  84358402         M

Row Selection

Know the column names

In [9]:
# syntax = variable.loc [ row_selection, column_selection_by_column_names]
# starting from 0-> 3rd row, and 3 columns-> id, diagnosis and radius_mean
newdata = data.loc[ 2, ['id', 'diagnosis', 'radius_mean']]
newdata.head()

id             84300903
diagnosis             M
radius_mean       19.69
Name: 2, dtype: object

In [10]:
# From 10th Row (11th from 0), till 12th Row 
# from, to 
newdata = data.loc[ 10:12, ['id', 'radius_mean']]
newdata.head()

          id  radius_mean
10    845636        16.02
11  84610002        15.78
12    846226        19.17

In [12]:
# From beginning, till 12th Row 
# from, to 
newdata = data.loc[ :12, ['id', 'radius_mean']]
newdata

          id  radius_mean
0     842302        17.99
1     842517        20.57
2   84300903        19.69
3   84348301        11.42
4   84358402        20.29
5     843786        12.45
6     844359        18.25
7   84458202        13.71
8     844981        13.00
9   84501001        12.46
10    845636        16.02
11  84610002        15.78
12    846226        19.17

In [14]:
# From  560th Row , till the end
# from, to 
newdata = data.loc[ 560:, ['id', 'radius_mean']]
newdata

         id  radius_mean
560  925292        14.05
561  925311        11.20
562  925622        15.22
563  926125        20.92
564  926424        21.56
565  926682        20.13
566  926954        16.60
567  927241        20.60
568   92751         7.76

Know the column index

In [15]:
# All rows represented by :
# only columns 2 to 4 [5 excluded]
newdata = data.iloc[:, 2:5]
newdata

     radius_mean  texture_mean  perimeter_mean
0          17.99         10.38          122.80
1          20.57         17.77          132.90
2          19.69         21.25          130.00
3          11.42         20.38           77.58
4          20.29         14.34          135.10
..           ...           ...             ...
564        21.56         22.39          142.00
565        20.13         28.25          131.20
566        16.60         28.08          108.30
567        20.60         29.33          140.10
568         7.76         24.54           47.92

[569 rows x 3 columns]

In [19]:
# if we use negative indexing, calculation is from bottom and right
# -5: will give me last 5 records (rows)
# -3 will give me last three columns 
newdata = data.iloc[-5:, -3:]
newdata

     symmetry_worst  fractal_dimension_worst  Unnamed: 32
564          0.2060                  0.07115          NaN
565          0.2572                  0.06637          NaN
566          0.2218                  0.07820          NaN
567          0.4087                  0.12400          NaN
568          0.2871                  0.07039          NaN

STATISTICS

 mean, median, mode, correlation, min, max, standard_deviation, variance

In [20]:
data.describe()

,id,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
count,5.690000e+02,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,...,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,0.0
mean,3.037183e+07,14.127292,19.289649,91.969033,654.889104,0.096360,0.104341,0.088799,0.048919,0.181162,...,25.677223,107.261213,880.583128,0.132369,0.254265,0.272188,0.114606,0.290076,0.083946,NaN
std,1.250206e+08,3.524049,4.301036,24.298981,351.914129,0.014064,0.052813,0.079720,0.038803,0.027414,...,6.146258,33.602542,569.356993,0.022832,0.157336,0.208624,0.065732,0.061867,0.018061,NaN
min,8.670000e+03,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,...,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156500,0.055040,NaN
25%,8.692180e+05,11.700000,16.170000,75.170000,420.300000,0.086370,0.064920,0.029560,0.020310,0.161900,...,21.080000,84.110000,515.300000,0.116600,0.147200,0.114500,0.064930,0.250400,0.071460,NaN
50%,9.060240e+05,13.370000,18.840000,86.240000,551.100000,0.095870,0.092630,0.061540,0.033500,0.179200,...,25.410000,97.660000,686.500000,0.131300,0.211900,0.226700,0.099930,0.282200,0.080040,NaN
75%,8.813129e+06,15.780000,21.800000,104.100000,782.700000,0.105300,0.130400,0.130700,0.074000,0.195700,...,29.720000,125.400000,1084.000000,0.146000,0.339100,0.382900,0.161400,0.317900,0.092080,NaN
max,9.113205e+08,28.110000,39.280000,188.500000,2501.000000,0.163400,0.345400,0.426800,0.201200,0.304000,...,49.540000,251.200000,4254.000000,0.222600,1.058000,1.252000,0.291000,0.663800,0.207500,NaN

In [21]:
mystats = data.describe()
mystats['radius_mean']

count    569.000000
mean      14.127292
std        3.524049
min        6.981000
25%       11.700000
50%       13.370000
75%       15.780000
max       28.110000
Name: radius_mean, dtype: float64

In [22]:
data.describe().T

,count,mean,std,min,25%,50%,75%,max
id,569.0,3.037183e+07,1.250206e+08,8670.000000,869218.000000,906024.000000,8.813129e+06,9.113205e+08
radius_mean,569.0,1.412729e+01,3.524049e+00,6.981000,11.700000,13.370000,1.578000e+01,2.811000e+01
texture_mean,569.0,1.928965e+01,4.301036e+00,9.710000,16.170000,18.840000,2.180000e+01,3.928000e+01
perimeter_mean,569.0,9.196903e+01,2.429898e+01,43.790000,75.170000,86.240000,1.041000e+02,1.885000e+02
area_mean,569.0,6.548891e+02,3.519141e+02,143.500000,420.300000,551.100000,7.827000e+02,2.501000e+03
smoothness_mean,569.0,9.636028e-02,1.406413e-02,0.052630,0.086370,0.095870,1.053000e-01,1.634000e-01
compactness_mean,569.0,1.043410e-01,5.281276e-02,0.019380,0.064920,0.092630,1.304000e-01,3.454000e-01
concavity_mean,569.0,8.879932e-02,7.971981e-02,0.000000,0.029560,0.061540,1.307000e-01,4.268000e-01
concave points_mean,569.0,4.891915e-02,3.880284e-02,0.000000,0.020310,0.033500,7.400000e-02,2.012000e-01
symmetry_mean,569.0,1.811619e-01,2.741428e-02,0.106000,0.161900,0.179200,1.957000e-01,3.040000e-01
fractal_dimension_mean,569.0,6.279761e-02,7.060363e-03,0.049960,0.057700,0.061540,6.612000e-02,9.744000e-02
radius_se,569.0,4.051721e-01,2.773127e-01,0.111500,0.232400,0.324200,4.789000e-01,2.873000e+00
texture_se,569.0,1.216853e+00,5.516484e-01,0.360200,0.833900,1.108000,1.474000e+00,4.885000e+00
perimeter_se,569.0,2.866059e+00,2.021855e+00,0.757000,1.606000,2.287000,3.357000e+00,2.198000e+01
area_se,569.0,4.033708e+01,4.549101e+01,6.802000,17.850000,24.530000,4.519000e+01,5.422000e+02
smoothness_se,569.0,7.040979e-03,3.002518e-03,0.001713,0.005169,0.006380,8.146000e-03,3.113000e-02
compactness_se,569.0,2.547814e-02,1.790818e-02,0.002252,0.013080,0.020450,3.245000e-02,1.354000e-01
concavity_se,569.0,3.189372e-02,3.018606e-02,0.000000,0.015090,0.025890,4.205000e-02,3.960000e-01
concave points_se,569.0,1.179614e-02,6.170285e-03,0.000000,0.007638,0.010930,1.471000e-02,5.279000e-02
symmetry_se,569.0,2.054230e-02,8.266372e-03,0.007882,0.015160,0.018730,2.348000e-02,7.895000e-02
fractal_dimension_se,569.0,3.794904e-03,2.646071e-03,0.000895,0.002248,0.003187,4.558000e-03,2.984000e-02
radius_worst,569.0,1.626919e+01,4.833242e+00,7.930000,13.010000,14.970000,1.879000e+01,3.604000e+01
texture_worst,569.0,2.567722e+01,6.146258e+00,12.020000,21.080000,25.410000,2.972000e+01,4.954000e+01
perimeter_worst,569.0,1.072612e+02,3.360254e+01,50.410000,84.110000,97.660000,1.254000e+02,2.512000e+02
area_worst,569.0,8.805831e+02,5.693570e+02,185.200000,515.300000,686.500000,1.084000e+03,4.254000e+03
smoothness_worst,569.0,1.323686e-01,2.283243e-02,0.071170,0.116600,0.131300,1.460000e-01,2.226000e-01
compactness_worst,569.0,2.542650e-01,1.573365e-01,0.027290,0.147200,0.211900,3.391000e-01,1.058000e+00
concavity_worst,569.0,2.721885e-01,2.086243e-01,0.000000,0.114500,0.226700,3.829000e-01,1.252000e+00
concave points_worst,569.0,1.146062e-01,6.573234e-02,0.000000,0.064930,0.099930,1.614000e-01,2.910000e-01
symmetry_worst,569.0,2.900756e-01,6.186747e-02,0.156500,0.250400,0.282200,3.179000e-01,6.638000e-01
fractal_dimension_worst,569.0,8.394582e-02,1.806127e-02,0.055040,0.071460,0.080040,9.208000e-02,2.075000e-01
Unnamed: 32,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
# standard dev for all columns
mystats = data.describe().T
mystats['std']

id                         1.250206e+08
radius_mean                3.524049e+00
texture_mean               4.301036e+00
perimeter_mean             2.429898e+01
area_mean                  3.519141e+02
smoothness_mean            1.406413e-02
compactness_mean           5.281276e-02
concavity_mean             7.971981e-02
concave points_mean        3.880284e-02
symmetry_mean              2.741428e-02
fractal_dimension_mean     7.060363e-03
radius_se                  2.773127e-01
texture_se                 5.516484e-01
perimeter_se               2.021855e+00
area_se                    4.549101e+01
smoothness_se              3.002518e-03
compactness_se             1.790818e-02
concavity_se               3.018606e-02
concave points_se          6.170285e-03
symmetry_se                8.266372e-03
fractal_dimension_se       2.646071e-03
radius_worst               4.833242e+00
texture_worst              6.146258e+00
perimeter_worst            3.360254e+01
area_worst                 5.693570e+02
smoothness_worst           2.283243e-02
compactness_worst          1.573365e-01
concavity_worst            2.086243e-01
concave points_worst       6.573234e-02
symmetry_worst             6.186747e-02
fractal_dimension_worst    1.806127e-02
Unnamed: 32                         NaN
Name: std, dtype: float64

In [24]:
data.min()

id                             8670
diagnosis                         B
radius_mean                   6.981
texture_mean                   9.71
perimeter_mean                43.79
area_mean                     143.5
smoothness_mean             0.05263
compactness_mean            0.01938
concavity_mean                  0.0
concave points_mean             0.0
symmetry_mean                 0.106
fractal_dimension_mean      0.04996
radius_se                    0.1115
texture_se                   0.3602
perimeter_se                  0.757
area_se                       6.802
smoothness_se              0.001713
compactness_se             0.002252
concavity_se                    0.0
concave points_se               0.0
symmetry_se                0.007882
fractal_dimension_se       0.000895
radius_worst                   7.93
texture_worst                 12.02
perimeter_worst               50.41
area_worst                    185.2
smoothness_worst            0.07117
compactness_worst           0.02729
concavity_worst                 0.0
concave points_worst            0.0
symmetry_worst               0.1565
fractal_dimension_worst     0.05504
Unnamed: 32                     NaN
dtype: object

In [25]:
data.max()

id                         911320502
diagnosis                          M
radius_mean                    28.11
texture_mean                   39.28
perimeter_mean                 188.5
area_mean                     2501.0
smoothness_mean               0.1634
compactness_mean              0.3454
concavity_mean                0.4268
concave points_mean           0.2012
symmetry_mean                  0.304
fractal_dimension_mean       0.09744
radius_se                      2.873
texture_se                     4.885
perimeter_se                   21.98
area_se                        542.2
smoothness_se                0.03113
compactness_se                0.1354
concavity_se                   0.396
concave points_se            0.05279
symmetry_se                  0.07895
fractal_dimension_se         0.02984
radius_worst                   36.04
texture_worst                  49.54
perimeter_worst                251.2
area_worst                    4254.0
smoothness_worst              0.2226
compactness_worst              1.058
concavity_worst                1.252
concave points_worst           0.291
symmetry_worst                0.6638
fractal_dimension_worst       0.2075
Unnamed: 32                      NaN
dtype: object